kind: Deployment
apiVersion: apps/v1
metadata:
  name: animal-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animal-api
  template:
    metadata:
      labels:
        app: animal-api
    spec:
      containers:
        - name: animal-api
          image: jgaonaakm/animal-api:v1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
---
kind: Service
apiVersion: v1
metadata:
  name: animal-api
spec:
  type: LoadBalancer
  selector:
    app: animal-api
  ports:
    - port: 80
      targetPort: 8080
      